server:
  port: 8080
#  servlet:
#    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory
    username: root
    password: root
  data:
    rest:
      base-path: /api
      # retorna 20 elementos por página
      default-page-size: 3

logging:
  level:
    web: debug