server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory
    username: root
    password: root
  data:
    rest:
      base-path: /magic-api
      default-page-size: 20

logging:
  level:
    web: debug