### actuator
GET http://localhost:8080/actuator

### health
GET http://localhost:8080/actuator/health

### health-path
GET http://localhost:8080/actuator/health/{*path}

### info
GET http://localhost:8080/actuator/info

### auditevents - eventos de auditoria da aplicação
GET http://localhost:8080/actuator/auditevents

### beans - lista de todos os beans registrados no contexto do Spring
GET http://localhost:8080/actuator/beans

### mappings - lita todos os caminhos @RequestMapping
GET http://localhost:8080/actuator/mappings

### caches
GET http://localhost:8080/actuator/caches

### caches-cache
GET http://localhost:8080/actuator/caches/{cache}

### conditions
GET http://localhost:8080/actuator/conditions

### configprops
GET http://localhost:8080/actuator/configprops

### configprops-prefix
GET http://localhost:8080/actuator/configprops/{prefix}

### env
GET http://localhost:8080/actuator/env

### env-toMatch
GET http://localhost:8080/actuator/configprops/{toMatch}

### logfile
GET http://localhost:8080/actuator/logfile

### loggers
GET http://localhost:8080/actuator/loggers

### loggers-name
GET http://localhost:8080/actuator/loggers/{name}

### heapdump
GET http://localhost:8080/actuator/heapdump

### threaddump
GET http://localhost:8080/actuator/threaddump

### metrics
GET http://localhost:8080/actuator/metrics

### metrics-requiredMetricName
GET http://localhost:8080/actuator/metrics/{requiredMetricName}

### scheduledtasks
GET http://localhost:8080/actuator/scheduledtasks